### ISSUE TITLE
[Feature] Carbonfet thumb cluster

### ISSUE THREAD

**Issue by dunk2k** [rianadon/dactyl-configurator#11]
Would it be possible to add the [Carbonfet](https://github.com/carbonfet/dactyl-manuform) thumb cluster?

Thumb Key Count: `6 (Carbonfet)`

**Comment by rianadon** [comment]
It would definitely be feasible. At the same time, it would be no easy change. The layout of the carbonfet thumb cluster diverges from the manuform cluster, and merely publishing a new shaping preset would not be enough.

Even if all the keys were positioned correctly, the existing wall generation would attach the walls of the case to the wrong keys, resulting in lots of self-intersecting geometry and an ugly keyboard. The dactly code is written such that all the walls are laid out by hand, and adding a new custom thumb cluster is a code-and-time-intensive feat (the [diff of carbonfet's `src/dactyl_keyboard/dactly.clj`](https://github.com/l4u/dactyl-manuform-mini-keyboard/compare/master...carbonfet:dactyl-manuform:master#diff-8ab16a031568e6c3e9b50873cc03e8bedd022f2a2d9259ce97d4830119e51b70) shows roughly what's required).

Personally I'd much prefer an algorithm to solve wall positioning rather than writing it out by hand for every custom thumb cluster, and that's one of the chief reasons I created the [Cosmos Keyboard Generator](ryanis.cool/cosmos/). If you haven't already played with it I suggest you give the beta a try or wait until it's released. The models are similar to the dactyl and there's Carbonfet thumb clusters and much much more :)

I'm not opposed to accepting a PR that added Carbonfet thumb clusters, but I fear the burden of maintaining the hundred lines of code per additional new thumb cluster. I'm going to close this as I don't intend on adding new custom thumb clusters here.

**Comment by dunk2k** [comment]
A genuinely insightful response, many thanks 🙂

**Comment by rianadon** [comment]
Thank you! I like to give some substance to my vetos.

I also just saw you joined the Cosmos discord server. Welcome!
