### ISSUE TITLE
Unable to Generate Original Dactyl case

### ISSUE THREAD

**Issue by mmillis1** [rianadon/dactyl-configurator#18]
Hello, love the project!

I do see the warning when selecting original dactyl `Generating the Original Dactyl case takes an extremeley long time, so it is disabled by default. Turn on Include Case to generate it.`, but after waiting several hours, it never previewed or was able to download.

Is there any work-around for being able to download the STL of the original dactyl case even if the preview is unavailable? 

URL: https://ryanis.cool/dactyl/#original:ChIIBhABGAEiA2JveCoDc2l4MAAqCAgAEAEYASAA

console output from load of webpage, waiting a few minutes, then trying to download the model

![image](https://github.com/user-attachments/assets/0287f371-2796-4a72-818a-4ad61cb2abe9)

Tried to generate model on both Brave and Firefox with the same errors

**Comment by rianadon** [comment]
I've seen this too. It's not an issue on your end. What you could do as a workaround is download the OpenSCAD file instead of the STL, then download OpenSCAD and use that to render the model. You could also use the button in the generator to use the WASM-based OpenSCAD to do the render, but it will be slower than the desktop application.

That said, don't get your hopes up. The version of the clojure code I'm working with doesn't actually generate the original case, but instead a mishmash of manuform-style walls with the original project's key layout.

<img width="355" alt="image" src="https://github.com/user-attachments/assets/4c86f0bd-9f12-475f-bae2-2b5956c42adb">
 
If you're trying to generate the original design, I recommend porting over your customizations to [the original project](https://github.com/adereth/dactyl-keyboard/blob/master/src/dactyl_keyboard/dactyl.clj). Unfortunately it wasn't written to be easily customizable, so you'll have to hunt for the variables you need. Or just download the closest looking model from the [`things`](https://github.com/adereth/dactyl-keyboard/tree/master/things) directory :D Especially since what you have looks very similar to the original layout.

If you're looking for more customization, I'd suggest you try [Cosmos](https://ryanis.cool/cosmos/) which is the spiritual successor to this project. There's a few different case designs that are [free and open-source](https://github.com/rianadon/Cosmos-Keyboards/) and you get a whole lot more customization (like adding trackballs/pads/displays and dragging keys to wherever you want them). However, stilts mode, which is closest to the original manuform design, is not free.

**Comment by mmillis1** [comment]
Thank you very much! I'll try that but def looking into Cosmos right now :)

Thanks for all your work!
