### ISSUE TITLE
Nomenclature

### ISSUE THREAD

**Issue by dunk2k** [rianadon/dactyl-configurator#7]
Hi @rianadon,

Not sure If I'm being a purist/pedantic but this, small, point came to my attention recently when assisting some prototyping work using this generator. 

This generator names what is the original (gangster) Dactyl as 'Lightcycle'. The actual Dactyl Lightcycle is a smaller variant of the Dactyl.  

What would be your view on changing the code/front end to rename 'Lightcycle' as 'Dactyl', and have 2 presets:
1. 'Original'
2. 'Lightcycle'

P.S. this generator is exactly what has been needing for years; a one stop shop for configuring and printing dactyls - **sincerely, thank you!**

**Comment by rianadon** [comment]
Hello! It's the pedantic type of suggestion but it passes my pedantism filter. Thank you for the name clarifications. I do prefer naming things correctly, especially the work of others.

I do like the idea of having two presets for the original dactyl and renaming the current preset to "Lightcycle". But maybe instead of renaming the "Lightcycle" as "Dactyl", maybe something like "Original Dactyl" since I've seen the Dactyl Manuform called simply "Dactyl" a lot too.

> P.S. this generator is exactly what has been needing for years; a one stop shop for configuring and printing dactyls - sincerely, thank you!

I really appreciate the gratitude. Thank _you_!
